/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.thefletcher.tbaapi.v3client.model.APIStatusAppVersion;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for APIStatus
 */
public class APIStatusTest {
    private final APIStatus model = new APIStatus();

    /**
     * Model tests for APIStatus
     */
    @Test
    public void testAPIStatus() {
        // TODO: test APIStatus
    }

    /**
     * Test the property 'currentSeason'
     */
    @Test
    public void currentSeasonTest() {
        // TODO: test currentSeason
    }

    /**
     * Test the property 'maxSeason'
     */
    @Test
    public void maxSeasonTest() {
        // TODO: test maxSeason
    }

    /**
     * Test the property 'isDatafeedDown'
     */
    @Test
    public void isDatafeedDownTest() {
        // TODO: test isDatafeedDown
    }

    /**
     * Test the property 'downEvents'
     */
    @Test
    public void downEventsTest() {
        // TODO: test downEvents
    }

    /**
     * Test the property 'ios'
     */
    @Test
    public void iosTest() {
        // TODO: test ios
    }

    /**
     * Test the property 'android'
     */
    @Test
    public void androidTest() {
        // TODO: test android
    }

}
