/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.thefletcher.tbaapi.v3client.model.DistrictRankingEventPoints;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DistrictRanking
 */
public class DistrictRankingTest {
    private final DistrictRanking model = new DistrictRanking();

    /**
     * Model tests for DistrictRanking
     */
    @Test
    public void testDistrictRanking() {
        // TODO: test DistrictRanking
    }

    /**
     * Test the property 'teamKey'
     */
    @Test
    public void teamKeyTest() {
        // TODO: test teamKey
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'rookieBonus'
     */
    @Test
    public void rookieBonusTest() {
        // TODO: test rookieBonus
    }

    /**
     * Test the property 'pointTotal'
     */
    @Test
    public void pointTotalTest() {
        // TODO: test pointTotal
    }

    /**
     * Test the property 'eventPoints'
     */
    @Test
    public void eventPointsTest() {
        // TODO: test eventPoints
    }

}
