/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.thefletcher.tbaapi.v3client.model.WLTRecord;


import org.junit.jupiter.api.Test;


/**
 * Model tests for EliminationAllianceStatus
 */
class EliminationAllianceStatusTest {
    private final EliminationAllianceStatus model = new EliminationAllianceStatus();

    /**
     * Model tests for EliminationAllianceStatus
     */
    @Test
    void testEliminationAllianceStatus() {
        // TODO: test EliminationAllianceStatus
    }

    /**
     * Test the property 'playoffAverage'
     */
    @Test
    void playoffAverageTest() {
        // TODO: test playoffAverage
    }

    /**
     * Test the property 'level'
     */
    @Test
    void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'record'
     */
    @Test
    void recordTest() {
        // TODO: test record
    }

    /**
     * Test the property 'currentLevelRecord'
     */
    @Test
    void currentLevelRecordTest() {
        // TODO: test currentLevelRecord
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

}
