/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.thefletcher.tbaapi.v3client.model.EliminationAllianceBackup;
import net.thefletcher.tbaapi.v3client.model.EliminationAllianceStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EliminationAlliance
 */
public class EliminationAllianceTest {
    private final EliminationAlliance model = new EliminationAlliance();

    /**
     * Model tests for EliminationAlliance
     */
    @Test
    public void testEliminationAlliance() {
        // TODO: test EliminationAlliance
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'backup'
     */
    @Test
    public void backupTest() {
        // TODO: test backup
    }

    /**
     * Test the property 'declines'
     */
    @Test
    public void declinesTest() {
        // TODO: test declines
    }

    /**
     * Test the property 'picks'
     */
    @Test
    public void picksTest() {
        // TODO: test picks
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
