/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.thefletcher.tbaapi.v3client.model.MatchSimpleAlliances;
import net.thefletcher.tbaapi.v3client.model.MatchVideos;


import org.junit.jupiter.api.Test;


/**
 * Model tests for Match
 */
class MatchTest {
    private final Match model = new Match();

    /**
     * Model tests for Match
     */
    @Test
    void testMatch() {
        // TODO: test Match
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'compLevel'
     */
    @Test
    void compLevelTest() {
        // TODO: test compLevel
    }

    /**
     * Test the property 'setNumber'
     */
    @Test
    void setNumberTest() {
        // TODO: test setNumber
    }

    /**
     * Test the property 'matchNumber'
     */
    @Test
    void matchNumberTest() {
        // TODO: test matchNumber
    }

    /**
     * Test the property 'alliances'
     */
    @Test
    void alliancesTest() {
        // TODO: test alliances
    }

    /**
     * Test the property 'winningAlliance'
     */
    @Test
    void winningAllianceTest() {
        // TODO: test winningAlliance
    }

    /**
     * Test the property 'eventKey'
     */
    @Test
    void eventKeyTest() {
        // TODO: test eventKey
    }

    /**
     * Test the property 'time'
     */
    @Test
    void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'actualTime'
     */
    @Test
    void actualTimeTest() {
        // TODO: test actualTime
    }

    /**
     * Test the property 'predictedTime'
     */
    @Test
    void predictedTimeTest() {
        // TODO: test predictedTime
    }

    /**
     * Test the property 'postResultTime'
     */
    @Test
    void postResultTimeTest() {
        // TODO: test postResultTime
    }

    /**
     * Test the property 'scoreBreakdown'
     */
    @Test
    void scoreBreakdownTest() {
        // TODO: test scoreBreakdown
    }

    /**
     * Test the property 'videos'
     */
    @Test
    void videosTest() {
        // TODO: test videos
    }

}
