/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.thefletcher.tbaapi.v3client.model.MatchSimpleAlliances;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MatchSimple
 */
public class MatchSimpleTest {
    private final MatchSimple model = new MatchSimple();

    /**
     * Model tests for MatchSimple
     */
    @Test
    public void testMatchSimple() {
        // TODO: test MatchSimple
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'compLevel'
     */
    @Test
    public void compLevelTest() {
        // TODO: test compLevel
    }

    /**
     * Test the property 'setNumber'
     */
    @Test
    public void setNumberTest() {
        // TODO: test setNumber
    }

    /**
     * Test the property 'matchNumber'
     */
    @Test
    public void matchNumberTest() {
        // TODO: test matchNumber
    }

    /**
     * Test the property 'alliances'
     */
    @Test
    public void alliancesTest() {
        // TODO: test alliances
    }

    /**
     * Test the property 'winningAlliance'
     */
    @Test
    public void winningAllianceTest() {
        // TODO: test winningAlliance
    }

    /**
     * Test the property 'eventKey'
     */
    @Test
    public void eventKeyTest() {
        // TODO: test eventKey
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'predictedTime'
     */
    @Test
    public void predictedTimeTest() {
        // TODO: test predictedTime
    }

    /**
     * Test the property 'actualTime'
     */
    @Test
    public void actualTimeTest() {
        // TODO: test actualTime
    }

}
