/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import net.thefletcher.tbaapi.v3client.model.WLTRecord;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TeamEventStatusRankRanking
 */
public class TeamEventStatusRankRankingTest {
    private final TeamEventStatusRankRanking model = new TeamEventStatusRankRanking();

    /**
     * Model tests for TeamEventStatusRankRanking
     */
    @Test
    public void testTeamEventStatusRankRanking() {
        // TODO: test TeamEventStatusRankRanking
    }

    /**
     * Test the property 'matchesPlayed'
     */
    @Test
    public void matchesPlayedTest() {
        // TODO: test matchesPlayed
    }

    /**
     * Test the property 'qualAverage'
     */
    @Test
    public void qualAverageTest() {
        // TODO: test qualAverage
    }

    /**
     * Test the property 'sortOrders'
     */
    @Test
    public void sortOrdersTest() {
        // TODO: test sortOrders
    }

    /**
     * Test the property 'record'
     */
    @Test
    public void recordTest() {
        // TODO: test record
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'dq'
     */
    @Test
    public void dqTest() {
        // TODO: test dq
    }

    /**
     * Test the property 'teamKey'
     */
    @Test
    public void teamKeyTest() {
        // TODO: test teamKey
    }

}
