/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;


import org.junit.jupiter.api.Test;


/**
 * Model tests for Team
 */
class TeamTest {
    private final Team model = new Team();

    /**
     * Model tests for Team
     */
    @Test
    void testTeam() {
        // TODO: test Team
    }

    /**
     * Test the property 'key'
     */
    @Test
    void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'teamNumber'
     */
    @Test
    void teamNumberTest() {
        // TODO: test teamNumber
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'stateProv'
     */
    @Test
    void stateProvTest() {
        // TODO: test stateProv
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'gmapsPlaceId'
     */
    @Test
    void gmapsPlaceIdTest() {
        // TODO: test gmapsPlaceId
    }

    /**
     * Test the property 'gmapsUrl'
     */
    @Test
    void gmapsUrlTest() {
        // TODO: test gmapsUrl
    }

    /**
     * Test the property 'lat'
     */
    @Test
    void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lng'
     */
    @Test
    void lngTest() {
        // TODO: test lng
    }

    /**
     * Test the property 'locationName'
     */
    @Test
    void locationNameTest() {
        // TODO: test locationName
    }

    /**
     * Test the property 'website'
     */
    @Test
    void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'rookieYear'
     */
    @Test
    void rookieYearTest() {
        // TODO: test rookieYear
    }

    /**
     * Test the property 'motto'
     */
    @Test
    void mottoTest() {
        // TODO: test motto
    }

    /**
     * Test the property 'homeChampionship'
     */
    @Test
    void homeChampionshipTest() {
        // TODO: test homeChampionship
    }

}
