/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.04.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;


import org.junit.jupiter.api.Test;


/**
 * Model tests for TeamEventStatusAllianceBackup
 */
class TeamEventStatusAllianceBackupTest {
    private final TeamEventStatusAllianceBackup model = new TeamEventStatusAllianceBackup();

    /**
     * Model tests for TeamEventStatusAllianceBackup
     */
    @Test
    void testTeamEventStatusAllianceBackup() {
        // TODO: test TeamEventStatusAllianceBackup
    }

    /**
     * Test the property 'out'
     */
    @Test
    void outTest() {
        // TODO: test out
    }

    /**
     * Test the property 'in'
     */
    @Test
    void inTest() {
        // TODO: test in
    }

}
