/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;


import org.junit.jupiter.api.Test;


/**
 * Model tests for ZebraTeam
 */
class ZebraTeamTest {
    private final ZebraTeam model = new ZebraTeam();

    /**
     * Model tests for ZebraTeam
     */
    @Test
    void testZebraTeam() {
        // TODO: test ZebraTeam
    }

    /**
     * Test the property 'teamKey'
     */
    @Test
    void teamKeyTest() {
        // TODO: test teamKey
    }

    /**
     * Test the property 'xs'
     */
    @Test
    void xsTest() {
        // TODO: test xs
    }

    /**
     * Test the property 'ys'
     */
    @Test
    void ysTest() {
        // TODO: test ys
    }

}
