/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.api;

import net.thefletcher.tbaapi.v3client.ApiException;
import net.thefletcher.tbaapi.v3client.model.Match;
import net.thefletcher.tbaapi.v3client.model.MatchSimple;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MatchApi
 */
@Disabled
class MatchApiTest {

    private final MatchApi api = new MatchApi();

    
    /**
     * 
     *
     * Gets an array of Match Keys for the given event key that have timeseries data. Returns an empty array if no matches have timeseries data. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getEventMatchTimeseriesTest() throws ApiException {
        String eventKey = null;
        String ifModifiedSince = null;
        List<String> response = api.getEventMatchTimeseries(eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of matches for the given event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getEventMatchesTest() throws ApiException {
        String eventKey = null;
        String ifModifiedSince = null;
        List<Match> response = api.getEventMatches(eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of match keys for the given event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getEventMatchesKeysTest() throws ApiException {
        String eventKey = null;
        String ifModifiedSince = null;
        List<String> response = api.getEventMatchesKeys(eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a short-form list of matches for the given event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getEventMatchesSimpleTest() throws ApiException {
        String eventKey = null;
        String ifModifiedSince = null;
        List<MatchSimple> response = api.getEventMatchesSimple(eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a &#x60;Match&#x60; object for the given match key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getMatchTest() throws ApiException {
        String matchKey = null;
        String ifModifiedSince = null;
        Match response = api.getMatch(matchKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a short-form &#x60;Match&#x60; object for the given match key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getMatchSimpleTest() throws ApiException {
        String matchKey = null;
        String ifModifiedSince = null;
        MatchSimple response = api.getMatchSimple(matchKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets an array of game-specific Match Timeseries objects for the given match key or an empty array if not available. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getMatchTimeseriesTest() throws ApiException {
        String matchKey = null;
        String ifModifiedSince = null;
        List<Object> response = api.getMatchTimeseries(matchKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of matches for the given team and event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamEventMatchesTest() throws ApiException {
        String teamKey = null;
        String eventKey = null;
        String ifModifiedSince = null;
        List<Match> response = api.getTeamEventMatches(teamKey, eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of match keys for matches for the given team and event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamEventMatchesKeysTest() throws ApiException {
        String teamKey = null;
        String eventKey = null;
        String ifModifiedSince = null;
        List<String> response = api.getTeamEventMatchesKeys(teamKey, eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a short-form list of matches for the given team and event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamEventMatchesSimpleTest() throws ApiException {
        String teamKey = null;
        String eventKey = null;
        String ifModifiedSince = null;
        List<Match> response = api.getTeamEventMatchesSimple(teamKey, eventKey, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of matches for the given team and year.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamMatchesByYearTest() throws ApiException {
        String teamKey = null;
        Integer year = null;
        String ifModifiedSince = null;
        List<Match> response = api.getTeamMatchesByYear(teamKey, year, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a list of match keys for matches for the given team and year.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamMatchesByYearKeysTest() throws ApiException {
        String teamKey = null;
        Integer year = null;
        String ifModifiedSince = null;
        List<String> response = api.getTeamMatchesByYearKeys(teamKey, year, ifModifiedSince);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a short-form list of matches for the given team and year.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getTeamMatchesByYearSimpleTest() throws ApiException {
        String teamKey = null;
        Integer year = null;
        String ifModifiedSince = null;
        List<MatchSimple> response = api.getTeamMatchesByYearSimple(teamKey, year, ifModifiedSince);

        // TODO: test validations
    }
    
}
